<div id="game-sudoku">
    <div class="game-title">Sudoku</div>
    <div class="difficulties">
        <select class="select-difficulties">
            <?php
            $titleTemplate = '%s (%s open cells)';
            $currentDifficulty = $this->sudoku->getDifficulty();
            ?>
            <?php foreach ($this->difficulties as $code => $difficulty): ?>
                <?php
                    $openCells = $difficulty['openCells'];
                    if (is_array($openCells)) {
                        $openCells = $openCells['min'] . '..' . $openCells['max'];
                    }
                    $title = sprintf($titleTemplate, $difficulty['title'], $openCells);
                    $selected = $currentDifficulty == $code ? ' selected="selected"' : '';
                ?>
                <option value="<?php echo $code; ?>"<?php echo $selected; ?>><?php echo $title; ?></option>
            <?php endforeach; ?>
        </select>
        <button class="btn btn-mini btn-danger new-game">New game</button>
    </div>
    <?php echo $this->partial('_extra/sudoku-board.phtml'); ?>
</div>