<?php
$selectedDifficulty = isset($this->selectedDifficulty) ? $this->selectedDifficulty : 0;;
$selectedDifficulty = $this->difficulties[$selectedDifficulty];
$titleTemplate = '%s (%s открытых клеток)';
?>
<div class="create-new-game-container">
    <div class="difficulties">
        <form class="create-new-game ajax-form-submit form-inline" method="post" action="<?php echo $this->url(['action' => 'create'], 'sudoku', true); ?>">
            <input type="hidden" name="submit" value="1">
            <div class="form-message hidden"></div>
            <select class="select-difficulties" name="difficulty">
                <?php foreach ($this->difficulties as $difficulty): ?>
                    <?php
                        $openCells = $difficulty['openCells'];
                        if (is_array($openCells)) {
                            $openCells = $openCells['min'] . '..' . $openCells['max'];
                        }
                        $title = sprintf($titleTemplate, $difficulty['title'], $openCells);
                        $selected = $selectedDifficulty['code'] == $difficulty['code'] ? ' selected="selected"' : '';
                    ?>
                    <option value="<?php echo $difficulty['code']; ?>"<?php echo $selected; ?>><?php echo $title; ?></option>
                <?php endforeach; ?>
            </select>
            <button type="submit" class="btn btn-danger submit-form">Начать новую игру</button>
        </form>
    </div>
    <div class="game-board-example">
        <div class="game-board-example-container">
            <?php echo $this->partial('_extra/sudoku-board.phtml', ['parameters' => $this->boardExample, 'hide' => true]); ?>
        </div>
        <span class="image-info">(Пример головоломки "Судоку")</span>
    </div>
</div>