<?php
if (isset($this->selectedDifficulty) && $this->difficulties[$this->selectedDifficulty]) {
    $selectedDifficulty = $this->difficulties[$this->selectedDifficulty];
} else {
    $selectedDifficulty = $this->difficulties[Application_Service_Game_Abstract::DEFAULT_GAME_DIFFICULTY];
}
$titleTemplate = '%s (%s открытых клеток)';
?>
<div class="create-new-game-container">
    <div class="difficulties">
        <form class="create-new-game ajax-form-submit form-inline" method="post" action="<?php echo $this->url(['action' => 'create'], 'sudoku', true); ?>">
            <input type="hidden" name="submitted" value="1">
            <div class="form-message hidden"></div>
            <select class="select-difficulties" name="difficulty">
                <?php foreach ($this->difficulties as $difficulty): ?>
                    <?php
                        $openCells = $difficulty['openCells'];
                        if (is_array($openCells)) {
                            $openCells = $openCells['min'] . '..' . $openCells['max'];
                        }
                        $title = sprintf($titleTemplate, $difficulty['title'], $openCells);
                        $selected = $selectedDifficulty['id'] == $difficulty['id'] ? ' selected="selected"' : '';
                    ?>
                    <option value="<?php echo $difficulty['id']; ?>"<?php echo $selected; ?>><?php echo $title; ?></option>
                <?php endforeach; ?>
            </select>
            <button type="submit" class="btn btn-danger submit-form">Начать новую игру</button>
        </form>
    </div>
    <div class="game-board-example-container medium">
        <div class="game-board-example">
            <?php echo $this->partial('_partials/sudoku-board.phtml', ['size' => 'medium', 'parameters' => $this->boardExample, 'hide' => true]); ?>
            <span class="image-info">(Пример головоломки "Судоку")</span>
        </div>
    </div>
</div>