<div class="content">
    <?php if ($this->user['id'] == $this->currentUser['id']): ?>
        <h1>История ваших игр</h1>
    <?php else: ?>
        <h1>История игр игрока <?php echo $this->user['full_name']; ?></h1>
    <?php endif; ?>

    <?php echo $this->render('index/user-games-history.ajax.phtml'); ?>

    <div class="to-top">
        <a href="" class="scroll-to-top">Вверх <i class="icon-chevron-up"></i></a>
    </div>
</div>


