<?php
$this->headLink()
    ->appendStylesheet('/css/bootstrap.css')
    ->appendStylesheet('/css/fontello/fontello.css')
    ->appendStylesheet('/css/fontello/animation.css')
    ->appendStylesheet('/css/styles.css');

$this->headScript()
    ->prependFile('/js/sudoku_board.js')
    ->prependFile('/js/sudoku.js')
    ->prependFile('/js/user.js')
    ->prependFile('/js/modal.js')
    ->prependFile('/js/game.js')
    ->prependFile('/js/websocket.js')
    ->prependFile('/js/common.js')
    ->prependFile('/js/form.js')
    ->prependFile('/js/global.js')
    ->prependFile('/js/bootstrap.js')
    ->prependFile('/js/jquery.md5.js')
    ->prependFile('/js/jquery-2.0.3.js')
;
?>
<?php header('Content-type: text/html; charset=utf-8'); ?>
<?php echo $this->doctype() ?>
<html>
<head>
<?php
    echo $this->headLink();
    echo $this->headTitle();
?>
</head>
<body class="<?php echo $this->pageCode; ?>">

<?php echo $this->render('_extra/navigation.phtml'); ?>

<div class="main-container" id="main-container">
    <div class="left-column">
        <div class="column-container">
            <?php echo $this->render('_columns/_left-column.phtml'); ?>
        </div>
    </div>
    <div class="center-column">
        <div class="content-blocker hide">
            <div class="blocker-backdrop"></div>
            <div class="blocker-content"></div>
        </div>

        <div class="column-container">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
    <div class="right-column">
        <div class="column-container">
            <?php echo $this->render('_columns/_right-column.phtml'); ?>
        </div>
    </div>
</div>

<div id="modal" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="ficon-cancel"></i></button>
        <h3></h3>
    </div>
    <div class="modal-body">
    </div>
</div>

<?php echo $this->render('_extra/login-modal.phtml'); ?>

<?php $this->headScript()->appendScript('window.$Modal = new window.Modal(\'#modal\');'); ?>

<?php echo $this->headScript(); ?>
</body>
</html>
