<div class="sudoku-controls">
    <div class="sudoku-controls-row">
        <button class="mark-mode btn btn-info" data-toggle="button" title="Клавиши: ~ OR *">Режим пометок</button>
    </div>
    <div class="sudoku-controls-row" title="Клавиши: 1-9 and 0">
        <div class="sudoku-numpad">
            <table>
                <?php /*
                    <tr>
                        <td colspan="3" class="close"><i class="icon-remove-circle"></i></td>
                    </tr>
                    */ ?>
                <?php $number = 1; ?>
                <?php for ($row = 1; $row <= 3; $row++): ?>
                    <tr>
                        <?php for ($col = 1; $col <= 3; $col++): ?>
                            <td class="number enabled" data-number="<?php echo $number; ?>">
                                <?php if ($number == 3): ?><?php endif; ?>
                                <?php echo $number; ?>
                            </td>
                            <?php $number++; ?>
                        <?php endfor; ?>
                    </tr>
                <?php endfor; ?>
                <tr>
                    <td class="number clear" colspan="3" data-number="" title="очистить поле">&#8212;</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="sudoku-controls-row btn-group">
        <button class="undo-move btn disabled" data-moves="" title="отменить ход"><i class="ficon-reply"></i></button>
        <button class="redo-move btn disabled" data-moves="" title="повторить ход"><i class="ficon-forward"></i></button>
    </div>
    <div class="sudoku-controls-row">
        <button class="check-field btn">Проверить поле</button>
    </div>
    <div class="sudoku-controls-row">
        <button class="clear-field btn btn-danger">Очистить поле</button>
    </div>
</div>
