<?php
/** @var Application_Model_Game_Sudoku $sudoku */
$sudoku = $this->sudoku;
?>
<div id="game-sudoku-<?php echo $sudoku->getHash(); ?>"
     class="sudoku-table"
     ondragstart="return false;"
     ondrop="return false;"
     data-selected-cell=""
     data-hovered-number=""
    >

    <div class="congratulations">
        <div class="message">
            Поздравляем!<br>
            Вы решили эту Судоку!
        </div>
    </div>

    <?php echo $this->partial('_partials/sudoku-board.phtml'); ?>

    <?php echo $this->partial('_partials/sudoku-controls.phtml'); ?>

    <div class="sudoku-game-info">
        <div class="time">
            Время игры: <div class="game-time">синхронизация...</div>
        </div>
        <?php
        $currentDifficulty = $sudoku->getDifficulty();
        $currentDifficulty = $sudoku->getService()->getAllDifficulties()[$currentDifficulty];
        $openCells = $currentDifficulty['openCells'];
        if (is_array($openCells)) {
            $openCells = $openCells['min'] . '..' . $openCells['max'];
        }
        $currentDifficultyText = sprintf('%s (%s открытых клеток)', $currentDifficulty['title'], $openCells);
        ?>
        <div class="game-difficulty">
            Сложность: <span class="current-difficulty"><?php echo $currentDifficultyText; ?></span>
        </div>
    </div>
</div>

