<?php
$cols = 9; // 1..9
$rows = 9;

$parameters = isset($this->parameters) && is_array($this->parameters) ? $this->parameters : [];

/**
 * @param int $row
 * @param int $col
 * @return bool
 */
$isGray = function ($row, $col) {
    $grayRow = (bool)(ceil($row / 3) % 2); // 111000111
    $grayCol = (bool)(ceil($col / 3) % 2); // 111000111
    $isGray = $grayRow == $grayCol;
    return $isGray;
};

/**
 * @param int $row
 * @param int $col
 */
$getCell = function($row, $col) use ($parameters, $isGray) {
    $classes = [
        'cell',
        'row-' . $row,
        'col-' . $col,
        $isGray($row, $col) ? 'gray' : '',
    ];
    $number = '';
    $coords = $row . $col;
    if (isset($parameters['openCells'][$coords])) {
        $number = $parameters['openCells'][$coords];
        $classes[] = 'locked';
    } elseif (isset($parameters['checkedCells'][$coords])) {
        $number = $parameters['checkedCells'][$coords];
        $classes[] = 'open';
    } else {
        $classes[] = 'open';
        $classes[] = 'empty';
    }
?>
<td
    class="<?php echo implode(' ', array_filter($classes)); ?>"
    data-row="<?php echo $row; ?>"
    data-col="<?php echo $col; ?>"
    data-number="<?php echo $number; ?>"
    >
    <?php echo $number; ?>
</td>
<?php
}; // $getCell
?>
<table class="sudoku-board">
    <?php for ($row = 1; $row <= $rows; $row++): ?>
    <tr>
        <?php for ($col = 1; $col <= $cols; $col++): ?>
            <?php $getCell($row, $col); ?>
        <?php endfor; ?>
    </tr>
    <?php endfor; ?>
</table>
