<?php
    $user = $this->currentUser;
    switch (true) {
        case !empty($user['full_name']) && $user['full_name'] != Application_Model_Db_Users::DEFAULT_USER_FULL_NAME:
            $greeting = $user['full_name'];
            break;
        case !empty($user['login']):
            $greeting = $user['login'];
            break;
        case !empty($user['email']):
            $greeting = $user['email'];
            break;
        default:
            $greeting = Application_Model_Db_Users::DEFAULT_USER_FULL_NAME;
            break;
    }

?>
<div class="user-info-block user-menu-closed">
    <div class="user-info-title-container">
        <span class="user-info-title">
            Привет, <?php echo $greeting; ?>.
            <?php if ($user['role_id'] == Application_Service_User::ROLE_GUEST): ?>
            Может <a href="" class="login-button">залогинишься</a>?
            <?php endif; ?>
            <i class="user-menu-open-icon icon-chevron-down"></i>
            <i class="user-menu-close-icon icon-chevron-up"></i>
        </span>
    </div>
    <div class="user-menu-container">
        <div class="user-menu">
            <ul class="unstyled">
                <li>
                    <a href="">что-то</a>
                </li>
                <li>
                    <a href="">что-то еще</a>
                </li>
                <li class="logout">
                    <a href="/user/logout">Разлогиниться</a>
                </li>
            </ul>
        </div>
    </div>
</div>

<?php echo $this->render('_extra/login-modal.phtml'); ?>