<?php
if (!empty($this->rightColumnModules) && is_array($this->rightColumnModules)) {
    foreach ($this->rightColumnModules as $module) {
        switch ($module) {
            case 'new-game-button':
                $content = $this->partial('_columns/new-game-button.phtml');
                break;

            case 'pause-game-button':
                $content = $this->partial('_columns/pause-game-button.phtml');
                break;

            case 'my-games-history':
                $parameters = [
                    'gamesHistory' => $this->gamesHistory,
                    'states'       => $this->states,
                ];
                $content = $this->partial('_columns/user-games-history.phtml', $parameters);
                break;

            case 'top-users-time':
                $parameters = [
                    'topUsersTimeDifficulty' => $this->topUsersTimeDifficulty,
                    'topUsersTime'           => $this->topUsersTime,
                    'difficulties'           => $this->difficulties,
                    'currentUser'            => $this->currentUser,
                ];
                $content = $this->partial('_columns/top-users-time.phtml', $parameters);
                break;

            case 'top-users-rating':
                $parameters = [
                    'topUsersRatingDifficulty' => $this->topUsersRatingDifficulty,
                    'topUsersRating'           => $this->topUsersRating,
                    'difficulties'             => $this->difficulties,
                    'currentUser'              => $this->currentUser,
                ];
                $content = $this->partial('_columns/top-users-rating.phtml', $parameters);
                break;

            default:
                $content = '';
        }
        echo $content;
    }
}

