<?php
$topUsersTimeDifficulty = $this->topUsersTimeDifficulty ? : Application_Service_Game_Sudoku::DEFAULT_GAME_DIFFICULTY;
$users = $this->topUsersTime;
$difficulties = $this->difficulties ? : [];
$currentUser = $this->currentUser;
?>
<?php if (!empty($users)): ?>
    <div class="section top-users-time-container">
        <div class="section-title">Быстрейшие игроки:</div>
        Сложность:
        <select
            name="top-users-time-difficulty"
            class="change-top-users-time-difficulty change-difficulty btn-small right-column-change-difficulty"
            data-action="<?php echo $this->url(['action' => 'get-top-users-time'], 'sudoku', true); ?>"
            data-container-class="top-users-time-container"
            >
            <?php foreach ($difficulties as $difficulty): ?>
                <?php $selected = $difficulty['id'] == $topUsersTimeDifficulty ? ' selected="selected"' : ''; ?>
                <option value="<?php echo $difficulty['id']; ?>"<?php echo $selected; ?>><?php echo $difficulty['title']; ?></option>
            <?php endforeach; ?>
        </select>
        <table class="top-users-game">
        <tbody>
        <tr class="head">
            <th>#</th>
            <th>Имя</th>
            <th>Время</th>
        </tr>
        <?php $i = 1; ?>
        <?php foreach ($users as $user): ?>
            <?php
            $duration = secondsToArray($user['faster_game_duration']);
            $time = isset($duration['seconds']) ? $duration['seconds'] : '';
            if (isset($duration['days'])) {
                $time = $duration['days'] . ' ' . ($duration['days'] > 1 ? 'дней' : 'день');
            } elseif (isset($duration['hours']) || isset($duration['minutes'])) {
                if (!isset($duration['hours'])) {
                    $time = intval($duration['minutes']) . ':' . $time;
                } else {
                    $time = $duration['hours'] . ':' . $duration['minutes'] . ':' . $time;
                }
            } else {
                // only seconds
                $time = intval($time);
                $last = intval(substr($time, -1));
                if ($last == 0 || ($time >= 5 && $time <= 19)) {
                    $time .= ' секунд'; // нуль секунд, пять секунд, четырнадцать секунд, двадцать секунд
                } elseif ($last == 1) {
                    $time .= ' секунда'; // одна секунда, двадцать одна секунда
                } elseif ($last < 5) {
                    $time .= ' секунды'; // две секунды, двадцать три секунды
                }
            }
            $even = (($i + 1) % 2) ? '' : ' even';
            $me = ($user['user_id'] == $this->currentUser['id']) ? ' me' : '';
            ?>
            <tr class="hlink<?php echo $even . $me; ?>" data-href="<?php echo $this->url(['gameHash' => $user['faster_game_hash']], 'sudoku-game', true); ?>">
                <td class="user-position"><?php echo $i; ?></td>
                <td class="user-full-name"><?php //echo $user['full_name']; ?></td>
                <td class="time"><?php echo $time; ?></td>
            </tr>
            <?php $i++; ?>
        <?php endforeach; ?>
        </tbody>
        </table>
        <div class="show-users-time-container">
            <a href="<?php echo $this->url(['action' => 'users-rating'], 'sudoku', true); ?>?sort=bestDuration&direction=desc" class="show-users-time">Просмотреть лучшее время всех игроков</a>
        </div>
    </div>
<?php endif; ?>