<?php
    $rows = 9;
    $cols = 9;

    $square = 0;
?>
<table class="game-board sudoku-board">

    <?php for ($r = 1; $r <= $rows; $r++): ?>
    <tr>

        <?php for ($c = 1; $c <= $cols; $c++): ?>

            <?php

            $s = (ceil($r / 3) - 1) * 3;
            $ss = ceil($c / 3);
            $square = $s + $ss;

            ?>

        <td class="sudoku-col col-<?php echo $c; ?> sudoku-row row-<?php echo $r; ?> sudoku-square square-<?php echo $square; ?>"></td>
        <?php endfor; ?>

    </tr>
    <?php endfor; ?>

</table>